---
- name: Configure | /etc/fuse.conf | user_allow_other
  lineinfile:
    state: present
    dest: /etc/fuse.conf
    regexp: '^#?user_allow_other'
    line: user_allow_other
  tags:
    - configuration
    - fuse

- name: "Create Group | %{{ riofs_group }}"
  group:
    name: "{{ riofs_group }}"
    system: yes
  when: riofs_group != 'root'

- name: "Create User | %{{ riofs_user }}"
  user:
    name: "{{ riofs_user }}"
    group: "{{ riofs_group }}"
    groups: fuse
    system: yes
  when: riofs_user != 'root'

- name: "Add User {{ item }} to %{{ riofs_group }}"
  user:
    name: "{{ item }}"
    groups: "{{ riofs_group }}"
    append: yes
  with_items: riofs_users

- name: Upload Config | RioFS
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: "{{ riofs_user }}"
    group: wcadmin
    mode: 0775
  with_items:
    - usr/local/etc/riofs/riofs.conf.xml
  notify: Reload Service | riofs
  tags:
    - configuration
    - template-configuration
